service: apollo-lambda
provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors: true
functions:
  graphql:
    handler: src/server.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST

custom:
  build.esbuild: false
