AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  MyPuppet:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      MemorySize: 1024
      Timeout: 100
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET