AwsTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  PuppeteerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/server.graphqlHandler
      Runtime: nodejs20.x
      Description: My Lambda function
      MemorySize: 512
      Timeout: 100
      Events:
        GraphQLApi:
          Type: Api
          Properties:
            Path: /graphql
            Method: POST